#
# \brief Default Travis for project
# \author Uilian Ries <uilianries@gmail.com>
#
dist: trusty

language: cpp

compiler: gcc

before_install:
  - sudo pip install conan
  - git clone https://github.com/uilianries/MQTTClient.git
  - cd MQTTClient
  - mkdir build 
  - cd build
  - conan install ..
  - cmake .. -DTESTS=OFF -DSAMPLES=OFF
  - cmake --build .
  - sudo make install
  - cd ../.. 

script:
  - mkdir build && cd build
  - conan install ..
  - cmake ..
  - cmake --build .
  - sudo make install

branches:
  only:
    - master
    - develop
