#
# \brief Default Travis for project
# \author Uilian Ries <uilianries@gmail.com>
#
dist: trusty

language: cpp

compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

before_install:
  - sudo pip install conan
  - git clone https://github.com/uilianries/MQTTClient.git
  - cd MQTTClient
  - mkdir build 
  - cd build
  - conan install ..
  - cmake .. -DTESTS=OFF -DSAMPLES=OFF
  - cmake --build .
  - sudo make install
  - cd ../.. 

install:
  if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - mkdir build && cd build
  - conan install ..
  - cmake ..
  - cmake --build .
  - sudo make install

branches:
  only:
    - master
    - develop
