#! /bin/sh

### BEGIN INIT INFO
# Provides:          smartaquarium-device-supervisor
# Required-Start:    $local_fs $remote_fs $syslog $network
# Required-Stop:     $local_fs $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Smart Aquarium Device Supervisor
# Description:       Execute daemon to listen MQTT broker and update the data base
### END INIT INFO

NAME=DeviceSupervisor
DAEMON=/usr/local/bin/$NAME
PIDFILE=/var/run/$NAME.pid
DAEMON_USER=root
DAEMON_OPTS=""
UPSTART_TIME=15

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

start_daemon() {
    log_daemon_msg "Starting Smart Aquarium: Device Supervisor"
    sleep $UPSTART_TIME
    LD_LIBRARY_PATH=/usr/local/lib start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
}

stop_daemon() {
    log_daemon_msg "Stopping Smart Aquarium: Device Supervisorr"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

status_daemon() {
    log_daemon_msg "Status Smart Aquarium: Device Supervisor"
    start-stop-daemon --status --pidfile $PIDFILE
    log_end_msg $?
}

case "$1" in
    start)
    start_daemon
    ;;
    stop)
    stop_daemon
    ;;
    status)
    status_daemon
    ;;
    restart)
    start_daemon
    stop_daemon
    ;;

    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac
exit 0

